# Generated by Django 3.0.7 on 2020-07-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
