# Generated by Django 3.0.7 on 2020-07-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0002_auto_20200723_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
