# Generated by Django 3.0.7 on 2020-07-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0003_auto_20200723_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='employe_id',
        ),
    ]
