# Generated by Django 3.0.7 on 2020-07-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0006_auto_20200725_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HrCompany',
        ),
    ]
