# Generated by Django 3.0.7 on 2020-07-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0007_delete_hrcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last',
        ),
    ]
