# Generated by Django 3.0.7 on 2020-07-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0008_auto_20200725_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first',
        ),
        migrations.AddField(
            model_name='employee',
            name='last',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
