# Generated by Django 3.0.7 on 2020-07-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0011_auto_20200726_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hr_agency_emp',
            new_name='user',
        ),
    ]
