# Generated by Django 3.0.7 on 2020-07-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0013_auto_20200726_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrcompany',
            old_name='company_name',
            new_name='company_user',
        ),
        migrations.AddField(
            model_name='hrcompany',
            name='hr_company_name',
            field=models.TextField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
