# Generated by Django 3.0.7 on 2020-08-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hr', '0016_auto_20200809_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='company',
        ),
    ]
